### ISSUE TITLE
Can you explain a bit more what this does?

### ISSUE THREAD

**Issue by scottjenson** [justinribeiro/is-justin-talking#1]
Could you expand the read.me just a bit so it's clear what this is doing (and what it takes to get running)? I'm intrigued by the idea of push notifications, how you trigger them from your slides and what you usually send. I could have several URLs in my talk and I'm worried that >3 notifications would get a bit old. 

However, I LOVE the idea. It even seems like almost-a-product (or at least a big feature of any web-based slides app.

All the best, great to see this!

Scott

**Comment by justinribeiro** [comment]
Hi Scott,

I was a little pressed for time when I pushed it as was running around trying to catch planes to get to the talk, so the instructions commit didn't land on time (no pun intended). :-) I've got an updated set of instructions I'm going to push into the repo today that should make the project a more workable.

The push portion was originally only meant to push updates about talks, but after I saw the tweet, I started working on a really simple piece of JavaScript that would push URL updates from slide changes from say reveal-js via GCM to people who have subscribed.

The basic flow becomes: 

PW Beacon to is-[person]-talking site > person sees site, subscribs for updates > slide change polls for subId's from Firebase, pushes via POST via GCM API key > subscribers get real time updates of important URLs / Information from app.

This is actually a really powerful in my mind as well; it becomes super interesting from a speaker standpoint (and I'm probably using it for a couple talks I have in March).

Cheers, Justin
